config/routes.rb
Rails.application.routes.draw do
  get 'reports/new'
  get 'reviews/new'
  get 'requests/index'
  get 'clients/index'
  get 'chefs/index'
  devise_for :users, :controllers => {:registrations => "my_devise/registrations"}
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'home#index'
  # get 'cities/:state', to: 'application#cities'

  # scope '/admins' do
  #   resources :users
  # end

  # resources :users do
    resources :clients do
      resources :requests
      resources :reports
    end
    resources :chefs do
      resources :galleries
      resources :services
    end
    # end
  resources :appointments do 
    resources :reviews
  end
    
  devise_scope :users do
    get '/client', to: 'clients#index', as: :client_root
    get '/client/:id', to: 'clients#profile', as: :client_profile
    get '/all_chefs', to: 'clients#all_chefs', as: :all_chefs
    put '/client/:id', to: 'clients#update_client'
    patch '/client/:id', to: 'clients#update_client'
    get '/client/:id/edit', to: 'clients#edit_client', as: :edit_client_profile

    get '/chef/:id', to: 'chefs#profile', as: :chef_profile
    get '/chef/:id/appointments', to: 'chefs#appointments', as: :chef_appointments
    get '/chef/:id/appointments/:id', to: 'chefs#notes_to_chef', as: :notes_to_chef
    get '/chef', to: 'chefs#index', as: :chef_root
    put '/chef/:id', to: 'chefs#update_chef'
    patch '/chef/:id', to: 'chefs#update_chef'
    get '/chef/:id/edit', to: 'chefs#edit_chef', as: :edit_chef_profile
    get '/chef/:id/appointments/:id/confirm', to: 'chefs#confirm_appointment', as: :confirm_appointment

    get '/admins', to: 'admins#index', as: :admin_root
    get '/admins/users', to: 'admins#all_users', as: :all_users
    get '/admins/reports', to: 'admins#reports'
    get '/admins/appointments', to: 'admins#appointments'
    get '/admins/transactions', to: 'admins#transactions'
    get '/admins/wallet', to: 'admins#admin_wallet'
    get '/admins/appointments/:id/release', to: 'admins#release_payment', as: :release_payment
    get '/admins/users/:id/suspend_chef', to: 'admins#suspend_chef', as: :suspend_chef
    get '/admins/users/:id/unsuspend_chef', to: 'admins#unsuspend_chef', as: :unsuspend_chef
    get '/admins/users/:id/suspend_client', to: 'admins#suspend_client', as: :suspend_client
    get '/admins/users/:id/unsuspend_client', to: 'admins#unsuspend_client', as: :unsuspend_client
  end

  get '/page-not-found', action: :error_page, controller: 'home'
  # get '*path', to: 'home#error_page'
  

  scope module: 'api', path: 'food', as: 'food' do
    get '/recipe/random', to: 'recipes#random'
  end
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)

    user ||= User.new
    if user.client? && !user.client.suspended_at?
      #can :manage, Client, user_id: user.id
      can :manage, Client
      can :manage, Chef
      can :manage, Request
      can :manage, Review
      # can :read, Portfolio, {:account_id => user.account.id}
      # can [:read, :update], Client, {:user_id => user.id}
      # can :manage, []
      # cannot :update, Wallet
    elsif user.chef? && !user.chef.suspended_at?
      #can :manage, Chef, user_id: user.id
      can :manage, Chef
      can :manage, Client
      can :show, Review
      can :manage, Report
    elsif user.admin?
      can :manage, :all
    else
      can :index, Chef
    end

    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  belongs_to :user
  has_one :wallet
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :chef
  belongs_to :request
  has_one :review, :dependent => :destroy
end

app/models/chef.rb
class Chef < ApplicationRecord
  validates :region, :city, :contact_number, presence: true

  belongs_to :user
  has_many :services
  has_many :appointments
  has_many :reports
  has_many :galleries
  has_one :wallet
end

app/models/client.rb
class Client < ApplicationRecord
  validates :region, :city, :contact_number, presence: true
  
  belongs_to :user
  has_many :requests
  has_many :reports
  has_one :wallet
end

app/models/gallery.rb
class Gallery < ApplicationRecord
  belongs_to :chef
  has_one_attached :image
end

app/models/report.rb
class Report < ApplicationRecord
  validates :message, presence: true

  belongs_to :chef
  belongs_to :client
end

app/models/request.rb
class Request < ApplicationRecord
  validates :head_count, :cuisine, presence: true

  belongs_to :client
  has_one :appointment
end

app/models/review.rb
class Review < ApplicationRecord
  validates :client_comment, :chef_rating, presence: true

  belongs_to :appointment
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles
  
  belongs_to :resource,
             :polymorphic => true,
             :optional => true
  

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/service.rb
class Service < ApplicationRecord
  validates :service_rate, presence: true

  belongs_to :chef


  def speciality_with_rate
    "#{specialty} - #{ActionController::Base.helpers.number_to_currency(service_rate, unit: "Php", precision: 2, delimiter: ",", format: "%u %n")}"
  end
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable
  validates :user_type, :first_name, :last_name, presence: true
  validates :username, uniqueness: true

  has_one :chef
  has_one :client
  has_one :admin
  has_one :wallet

  after_create :set_role, :create_account
  after_create :intialized_user_wallet
  
  def admin?
    has_role?(:admin)
  end

  def client?
    has_role?(:client)
  end

  def chef?
    has_role?(:chef)
  end

  def create_account
    if self.user_type == 'Admin'
      Admin.create(user: self)
    elsif self.user_type == 'Client'
      Client.create(user: self, region: 'Metro Manila', city: 'Amihan' , contact_number: '09748372837')
    elsif self.user_type == 'Chef'
      Chef.create(user: self, region: 'Metro Manila', city: 'Amihan' , contact_number: '09748372837', rating: 5)
    end
  end

  def set_role
    if self.user_type == 'Admin'
      self.add_role(:admin)
    elsif self.user_type == 'Client'
      self.add_role(:client)
    elsif self.user_type == 'Chef'
      self.add_role(:chef)
    end
  end

  def intialized_user_wallet
    wallet_amount = Wallet.new(user_id: id, current_balance: 20_000)
    wallet_amount.save
  end
end

app/models/wallet.rb
class Wallet < ApplicationRecord
  belongs_to :user
end

app/helpers/chefs_helper.rb
module ChefsHelper

  def charged(balance)
    balance = balance * 0.2
  end

  def payment(balance)
    balance = balance * 0.8
  end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admins/admin_wallet.html.haml
%h1{class:'text-3xl'} Admin Wallet


%h1{class:'text-3xl'}= @balance

app/views/admins/all_users.html.haml
%link(rel="stylesheet" type="text/css" href="users.scss");

.form
  %h1{class:'text-3xl'} Users List
  %table{:class => "w-full py-22 table text-gray-900 text-sm"}
    %thead{:class => "bg-gray-50 text-gray-500"}
      %tr
        %th{:class => "p-3 center"} Email
        %th{:class => "p-3 center"} Type
        %th{:class => "p-3 center"} Username
        %th{:class => "p-3 center"} First Name
        %th{:class => "p-3 center"} Last Name
        %th{:class => "p-3 center"} Region
        %th{:class => "p-3 center"} City
        %th{:class => "p-3 center"} Contact Number
        %th{:class => "p-3 center"} Date Latest Suspended
        %th{:class => "p-3 center"} Action
    %tbody
      - @users.each do |user|
        %tr{:class => "bg-white text-center border border-solid border-gray-300 outline-none shadow drop-shadow-xl"}
          %td{:class => "p-3 center"}= user.email
          %td{:class => "p-3 center"}= user.user_type
          %td{:class => "p-3 center"}
            - if user.user_type == "Client"
              = link_to "#{user.username}", client_profile_path(user.client.id)
            - elsif user.user_type == "Chef"
              = link_to "#{user.username}", chef_profile_path(user.chef.id)
          %td{:class => "p-3 center"}= user.first_name
          %td{:class => "p-3 center"}= user.last_name
          - if user.user_type == 'Client'
            %td{:class => "p-3 center"}= user.client.region
            %td{:class => "p-3 center"}= user.client.city
            %td{:class => "p-3 center"}= user.client.contact_number
            %td{:class => "p-3 center"}
              - if user.client.suspended_at
                = format_date(user.client.suspended_at)
              - else
                This user is fine.
            %td{:class => "p-3 center"}
              - if user.client.suspended_at
                = link_to 'Unsuspend?', unsuspend_client_path(user.client.id), class: "", data: {confirm:"Unsuspend this user?"}
              - else
                = link_to 'Suspend?', suspend_client_path(user.client.id), class: "", data: {confirm:"Suspend this user?"}

          - elsif user.user_type == 'Chef'
            %td{:class => "p-3 center"}= user.chef.region
            %td{:class => "p-3 center"}= user.chef.city
            %td{:class => "p-3 center"}= user.chef.contact_number
            %td{:class => "p-3 center"}
              - if user.chef.suspended_at
                = format_date(user.chef.suspended_at)
              - else
                This user is fine.
            %td{:class => "p-3 center"}
              - if user.chef.suspended_at
                = link_to 'Unsuspend?', unsuspend_chef_path(user.chef.id), class: "", data: {confirm:"Unsuspend this user?"}
              - else
                = link_to 'Suspend?', suspend_chef_path(user.chef.id), class: "", data: {confirm:"Suspend this user?"}

app/views/admins/appointments.html.haml
%link(rel="stylesheet" type="text/css" href="users.scss");



.form.appointments
  %h1{class:'text-3xl'} 
    Admin Balance: 
    = convert_to_money(@admin_wallet.current_balance)
  %h1{class:'text-3xl'} Appointments List
  %table
    %thead
      %tr
        %th Chef
        %th Client
        %th Created At
        %th Schedule
        %th Total Charge
        %th Confirmed At
        %th Payment Released At
        %th Release Payment?
        %th Action
    %tbody
      - @appointments.each do |a|
        %tr
          %td= link_to "#{a.chef.user.first_name} #{a.chef.user.last_name}", chef_profile_path(a.chef.id)
          %td= link_to "#{a.request.client.user.first_name} #{a.request.client.user.last_name}", client_profile_path(a.request.client.id)
          %td= format_date(a.created_at)
          %td
            - if a.schedule 
              = format_schedule(a.schedule)
              = format_schedule_time(a.appointment_time)
            - else
              No schedule yet
          %td= convert_to_money(a.total_charge)
          %td= a.confirmed_at ? format_date(a.confirmed_at) : "Not confirmed"
          %td
            - if a.payment_released_at 
              = format_date(a.payment_released_at)
            - else
              Payment not released yet.
          %td
            - if a.payment_released_at
              Payment has been released to the chef!
            - else
              - if a.confirmed_at?
                = link_to 'Release Payment?', release_payment_path(a.id), class: "", data: {confirm:"Are you sure?"}
          %td= link_to "Show the review", appointment_review_path(a.id, a.review.id), class: "text-black text-bold" if a.review

app/views/admins/index.html.erb
<div class='admin-homepage'>
  <div class='banner'>
    <h1 class='banner-header text-yellow-light'>
      Welcome Admin
    </h1>
    <h4>Ready to manage Cuisinero users and transactions?
      Begin by checking the reports made</h4>
  </div>
</>

app/views/admins/reports.html.haml
%link(rel="stylesheet" type="text/css" href="users.scss");

.form
  %h1{class:'text-3xl'} Reports List
  %table{:class => "w-full py-22 table text-gray-900 text-sm"}
    %thead{:class => "bg-gray-50 text-gray-500"}
      %tr
        %th{:class => "p-3 center"} Chef
        %th{:class => "p-3 center"} Client
        %th{:class => "p-3 center"} Message
    %tbody
      - @reports.each do |report|
        %tr{:class => "bg-white text-center border border-solid border-gray-300 outline-none shadow drop-shadow-xl"}
          %td{:class => "p-3 center"}= link_to "#{report.chef.user.username}", chef_profile_path(report.chef.id)
          %td{:class => "p-3 center"}= link_to "#{report.client.user.username}", client_profile_path(report.client.id)
          %td{:class => "p-3 center"}= report.message

app/views/admins/transactions.html.haml
%link(rel="stylesheet" type="text/css" href="users.scss");

.form
  %h1{class:'text-3xl'} Transaction List
  %table
    %thead
      - @appointments.each do |a|
        %tr
          - unless a.payment_released_at.nil?
            %td= "Total Payment of #{payment(a.total_charge)} and charged of #{charged(a.total_charge)} to the chef, #{a.chef.user.username}"

app/views/layouts/_footer.html.erb
<footer class="page-footer">
  <div class="container">
    <div class="row">
      <div class="col l6 s12">
        <h5 class="footer-text-white text-italic">© 2022 <span class="footer-text-yellow-dark">Cuisinero</span></h5>
        
        <ul>
          <li><a class="footer-text-white" href="#!">About us</a></li>
          <li><a class="footer-text-white" href="#!">FAQ</a></li>
          <li><a class="footer-text-white" href="#!">Contact us</a></li>
          <li><a class="footer-text-white" href="#!">More apps like this</a></li>
        </ul>
      </div>
      <div class="col l4 offset-l2 s12">
        <h5 class="footer-text-white text-italic">The Developers:</h5>
        <ul class='footer-list'>
          <li><a class="footer-text-yellow-light" href="#!">Ralph Sulit</a></li>
          <li><a class="footer-text-yellow-light" href="#!">John Carlo Martinez</a></li>
          <li><a class="footer-text-yellow-light" href="#!">Julie Mae Villanueva</a></li>
          <li><a class="footer-text-yellow-light" href="#!">Thea Kaylee Libunao</a></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="footer-copyright">
    <div class="container footer-disclaimer">
      Disclaimer: This app is created for educational purposes only.
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar-fixed"> 
  <nav>
    <div class="nav-wrapper">
      <%= link_to root_path do %>
        <%= image_tag "logo/logo.png", class: "brand-logo" %>
      <% end %>

      <a href="#" data-target="mobile-sidenav" class="sidenav-trigger right"><i class="material-icons">menu</i></a>

      <ul id="nav-mobile" class="right hide-on-med-and-down">
        <% if user_signed_in? && current_user.user_type == "Admin" %>
          <li>
            <%= link_to 'Users', all_users_path %>
          </li>
          <li>
            <%= link_to 'Reports', admins_reports_path %>
          </li>
          <li>
            <%= link_to 'Appointments', admins_appointments_path %>
          </li>
          <li>
            <%= link_to 'Transactions', admins_transactions_path %>
          </li>
          <li>
            <%= link_to(destroy_user_session_path, method: :delete, class: "waves-effect waves-light btn-large btn-black-dark") do %>
              Log Out <i class="material-icons right">arrow_forward</i>
            <% end %>
            <%#= link_to 'Logout', destroy_user_session_path, method: :delete, class: "emphasize-link" %>
          </li>
        
        <% elsif user_signed_in? && current_user.user_type == "Chef" %>
          <li>
            <%= link_to 'Profile', chef_profile_path(current_user.chef.id) %>
          </li>
          <li>
            <%= link_to 'Appointments', chef_appointments_path(current_user.chef.id) %>
          </li>
          <li>
            <%= link_to(destroy_user_session_path, method: :delete, class: "waves-effect waves-light btn-large btn-black-dark") do %>
              Log Out <i class="material-icons right">arrow_forward</i>
            <% end %>
            <%#= link_to 'Logout', destroy_user_session_path, method: :delete, class: "emphasize-link" %>
          </li>
        
        <% elsif user_signed_in? && current_user.user_type == "Client" %>
          <li>
            <%= link_to 'Profile', client_profile_path(current_user.client.id) %>
          </li>
          <li>
            <%= link_to 'Chefs', all_chefs_path %>
          </li>
          <li>
            <%= link_to(destroy_user_session_path, method: :delete, class: "waves-effect waves-light btn-large btn-black-dark") do %>
              Log Out <i class="material-icons right">arrow_forward</i>
            <% end %>
            <%#= link_to 'Logout', destroy_user_session_path, method: :delete, class: "emphasize-link" %>
          </li>
        
        <% else %>
          <li>
            <%= link_to 'Log In', new_user_session_path %>
          </li>
          <li>
            <%= link_to(new_user_registration_path, class: "waves-effect waves-light btn-large btn-yellow-dark") do %>
              Sign Up <i class="material-icons right">create</i>
            <% end %>
            <%#= link_to 'Sign Up', new_user_registration_path, class: "emphasize-link" %>
          </li>
        <% end %>    
      </ul>
    </div>
  </nav>
</header>

<ul id="mobile-sidenav" class="sidenav">
  <% if user_signed_in? && current_user.user_type == "Admin" %>
    <li class='sidenav-top-border'>
      <%= link_to 'Users', all_users_path %>
    </li>
    <li>
      <%= link_to 'Reports', admins_reports_path %>
    </li>
    <li>
      <%= link_to 'Appointments', admins_appointments_path %>
    </li>
    <li>
      <%= link_to 'Transactions', admins_transactions_path %>
    </li>
      <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: "emphasize-link" %>
    </li>
  
  <% elsif user_signed_in? && current_user.user_type == "Chef" %>
    <li class='sidenav-top-border'>
      <%= link_to 'Profile', chef_profile_path(current_user.chef.id) %>
    </li>
    <li>
      <%= link_to 'Appointments', chef_appointments_path(current_user.chef.id) %>
    </li>
    <li>
      <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: "emphasize-link" %>
    </li>
  
  <% elsif user_signed_in? && current_user.user_type == "Client" %>
    <li class='sidenav-top-border'>
      <%= link_to 'Profile', client_profile_path(current_user.client.id) %>
    </li>
    <li>
      <%= link_to 'Chefs', all_chefs_path %>
    </li>
    <li>
      <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: "emphasize-link" %>
    </li>
  
  <% else %>
    <li class='sidenav-top-border'>
      <%= link_to 'Log In', new_user_session_path %>
    </li>
    <li>
      <%= link_to 'Sign Up', new_user_registration_path, class: "emphasize-link" %>
    </li>
  <% end %>
</ul>

app/views/layouts/_profile_details.html.erb
<div class="section one"> 
  <div class="card-container">
    <div class="card">
      <div class="card-content text-space-sm">
        <div class="avatar">
          <img class="materialboxed" src="https://images.hdqwalls.com/download/angelina-jolie-4k-2019-new-3f-2560x1600.jpg">
        </div>
        <span class="card-title text-black-dark text-bold"><%= [current_user.first_name, current_user.last_name].join(' ') %></span>
        <p class="card-details text-black-light text-italic"><%#= @client.location %></p>
        <p class="card-details text-black-light"><%#= @client.contact_number %></p>
        
        <p class="card-details text-black-light text-italic">Tuguegarao City, Cagayan</p>
        <p class="card-details text-black-light">09261621023</p>
        
        <div class="rating-container text-yellow-dark">
          <% @rating = 4.5 %>
          <% if @rating >= 3 %>
            <% case @rating %>
            <% when 3 %>
              <i class="material-icons">star</i>
              <i class="material-icons">star</i>
              <i class="material-icons">star</i>
              <i class="material-icons">star_border</i>
              <i class="material-icons">star_border</i>
            <% when 3.5 %>
              <i class="material-icons">star</i>
              <i class="material-icons">star</i>
              <i class="material-icons">star</i>
              <i class="material-icons">star_half</i>
              <i class="material-icons">star_border</i>
            <% when 4 %>
              <i class="material-icons">star</i>
              <i class="material-icons">star</i>
              <i class="material-icons">star</i>
              <i class="material-icons">star</i>
              <i class="material-icons">star_border</i>
            <% when 4.5 %>
              <i class="material-icons">star</i>
              <i class="material-icons">star</i>
              <i class="material-icons">star</i>
              <i class="material-icons">star</i>
              <i class="material-icons">star_half</i>
            <% when 5 %>
              <i class="material-icons">star</i>
              <i class="material-icons">star</i>
              <i class="material-icons">star</i>
              <i class="material-icons">star</i>
              <i class="material-icons">star</i>
            <% end %>
            
          <% end %>
        </div>
        
        <% if current_user.user_type == 'Chef' %>
          <div class="divider"></div>
          
          <span class="card-title text-black-dark text-bold">Account balance:</span>
          <p class="card-details text-yellow-dark text-bold money"><%= convert_to_money(current_user.wallet.current_balance) %></p>

          <div class="btn-container">
            <%#= link_to(edit_chef_profile_path(@chef.id), class: "waves-effect waves-light btn-large") do %>
            <%= link_to(edit_user_registration_path(current_user.id), class: "waves-effect waves-light btn-large") do %>
              Edit Profile <i class="material-icons right">edit</i>
            <% end %> 
          </div>
        <% elsif current_user.user_type == 'Client' %>
          <div class="divider"></div>
          
          <span class="card-title text-black-dark text-bold">Account balance:</span>
          <p class="card-details text-yellow-dark text-bold money"><%= convert_to_money(current_user.wallet.current_balance) %></p>

          <div class="btn-container">
            <%#= link_to(edit_client_profile_path(@client.id), class: "waves-effect waves-light btn-large") do %>
            <%= link_to(edit_user_registration_path(current_user.id), class: "waves-effect waves-light btn-large") do %>
              Edit Profile <i class="material-icons right">edit</i>
            <% end %> 
          </div>
        <% else  %> 
        <% end %>

      </div>

    </div>
  </div>
</div>

app/views/profiles/_profile_public.html.erb
<div class="public section one"> 
  <div class="card-container">
    <div class="card">
      <div class="card-content text-space-sm">

        <% if !@chef.nil? %>
          <div class="avatar">
            <%= image_tag('chef-1.jpg', :class => 'materialboxed') %>
          </div>
          <span class="card-title text-black-dark text-bold">Chef <%= [@chef.user.first_name, @chef.user.last_name].join(' ') %></span>
          <p class="card-details text-black-light text-italic">
            <i class="material-icons left">location_on</i> <%= [@chef.city, @chef.region].join(', ') %>
          </p>
          <p class="card-details text-black-light"><i class="material-icons left">phone</i> <%= @chef.contact_number %></p>

          <div class="rating-container text-yellow-dark">
            <% if @rating %>
              <% case @rating %>
              <% when 0 %>
                <i class="material-icons">star_border</i>
                <i class="material-icons">star_border</i>
                <i class="material-icons">star_border</i>
                <i class="material-icons">star_border</i>
                <i class="material-icons">star_border</i>
              <% when 1 %>
                <i class="material-icons">star</i>
                <i class="material-icons">star_border</i>
                <i class="material-icons">star_border</i>
                <i class="material-icons">star_border</i>
                <i class="material-icons">star_border</i>
              <% when 2 %>
                <i class="material-icons">star</i>
                <i class="material-icons">star</i>
                <i class="material-icons">star_border</i>
                <i class="material-icons">star_border</i>
                <i class="material-icons">star_border</i>
              <% when 3 %>
                <i class="material-icons">star</i>
                <i class="material-icons">star</i>
                <i class="material-icons">star</i>
                <i class="material-icons">star_border</i>
                <i class="material-icons">star_border</i>
              <% when 4 %>
                <i class="material-icons">star</i>
                <i class="material-icons">star</i>
                <i class="material-icons">star</i>
                <i class="material-icons">star</i>
                <i class="material-icons">star_border</i>
              <% when 5 %>
                <i class="material-icons">star</i>
                <i class="material-icons">star</i>
                <i class="material-icons">star</i>
                <i class="material-icons">star</i>
                <i class="material-icons">star</i>
              <% end %>
            <% else %>
                <i class="material-icons">star_border</i>
                <i class="material-icons">star_border</i>
                <i class="material-icons">star_border</i>
                <i class="material-icons">star_border</i>
                <i class="material-icons">star_border</i>
            <% end %>
          </div>

          <% unless @chef.bio.nil? %>
            <div class="divider"></div>

            <div class="bio-container">
              <p class="card-details text-black-light text-italic">"<%= @chef.bio.truncate(100) %>"</p>
            </div>
          <% end %>
        
        <% elsif !@client.nil? %>
          <div class="avatar">
            <%= image_tag('avatar-5.jpg', :class => 'materialboxed') %>
          </div>
          <span class="card-title text-black-dark text-bold"><%= [@client.user.first_name, @client.user.last_name].join(' ') %></span>
          <p class="card-details text-black-light text-italic">
            <i class="material-icons left">location_on</i> <%= [@client.city, @client.region].join(', ') %>
          </p>
          <p class="card-details text-black-light"><i class="material-icons left">phone</i> <%= @client.contact_number %></p>
        <% end %>
      </div>
      <br>
      <br>
      <br>
      <br>
      <br>
      <div class="card-action">
        <% if !@chef.nil? %>
          <% if current_user.user_type == 'Client' %>
            <%= link_to(new_client_request_path(current_user.client.id, chef_id: @chef.id), class: "waves-effect waves-light btn-large btn-green") do %>
              Book Chef <i class="material-icons right">event</i>
            <% end %>
          <% end %>
          <!-- <%#= link_to(chef_path, class: "waves-effect waves-light btn-large btn-red") do %>
            Report <i class="material-icons right">block</i>
          <%# end %> -->
        <% elsif !@client.nil? %>
          <% if current_user.user_type == 'Chef' %>
          <!-- <%#= link_to(chefs_path, class: "waves-effect waves-light btn-large btn-green") do %>
              Rate <i class="material-icons right">rate_review</i>
              <%# end %> -->
          <% end %>
          <%= link_to(new_client_report_path(@client.id), class: "waves-effect waves-light btn-large btn-red") do %>
            Report <i class="material-icons right">block</i>
          <% end %>
        <% end %>
      </div>

    </div>
  </div>
</div>