config/routes.rb
Rails.application.routes.draw do
  get 'reports/new'
  get 'reviews/new'
  get 'requests/index'
  get 'clients/index'
  get 'chefs/index'
  devise_for :users, :controllers => {:registrations => "my_devise/registrations"}
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'home#index'
  # get 'cities/:state', to: 'application#cities'

  # scope '/admins' do
  #   resources :users
  # end

  # resources :users do
    resources :clients do
      resources :requests
      resources :reports
    end
    resources :chefs do
      resources :galleries
      resources :services
    end
    # end
  resources :appointments do 
    resources :reviews
  end
    
  devise_scope :users do
    get '/client', to: 'clients#index', as: :client_root
    get '/client/:id', to: 'clients#profile', as: :client_profile
    get '/all_chefs', to: 'clients#all_chefs', as: :all_chefs
    put '/client/:id', to: 'clients#update_client'
    patch '/client/:id', to: 'clients#update_client'
    get '/client/:id/edit', to: 'clients#edit_client', as: :edit_client_profile

    get '/chef/:id', to: 'chefs#profile', as: :chef_profile
    get '/chef/:id/appointments', to: 'chefs#appointments', as: :chef_appointments
    get '/chef/:id/appointments/:id', to: 'chefs#notes_to_chef', as: :notes_to_chef
    get '/chef', to: 'chefs#index', as: :chef_root
    put '/chef/:id', to: 'chefs#update_chef'
    patch '/chef/:id', to: 'chefs#update_chef'
    get '/chef/:id/edit', to: 'chefs#edit_chef', as: :edit_chef_profile
    get '/chef/:id/appointments/:id/confirm', to: 'chefs#confirm_appointment', as: :confirm_appointment

    get '/admins', to: 'admins#index', as: :admin_root
    get '/admins/users', to: 'admins#all_users', as: :all_users
    get '/admins/reports', to: 'admins#reports'
    get '/admins/appointments', to: 'admins#appointments'
    get '/admins/transactions', to: 'admins#transactions'
    get '/admins/wallet', to: 'admins#admin_wallet'
    get '/admins/appointments/:id/release', to: 'admins#release_payment', as: :release_payment
    get '/admins/users/:id/suspend_chef', to: 'admins#suspend_chef', as: :suspend_chef
    get '/admins/users/:id/unsuspend_chef', to: 'admins#unsuspend_chef', as: :unsuspend_chef
    get '/admins/users/:id/suspend_client', to: 'admins#suspend_client', as: :suspend_client
    get '/admins/users/:id/unsuspend_client', to: 'admins#unsuspend_client', as: :unsuspend_client
  end

  get '/page-not-found', action: :error_page, controller: 'home'
  # get '*path', to: 'home#error_page'
  

  scope module: 'api', path: 'food', as: 'food' do
    get '/recipe/random', to: 'recipes#random'
  end
end

app/models/chef.rb
class Chef < ApplicationRecord
  validates :region, :city, :contact_number, presence: true

  belongs_to :user
  has_many :services
  has_many :appointments
  has_many :reports
  has_many :galleries
  has_one :wallet
end

app/controllers/chefs_controller.rb
class ChefsController < ApplicationController

  before_action :set_chef, only: [:profile, :appointments, :edit_chef, :update_chef, :notes_to_chef]
  before_action :set_appointments, only: [:appointments, :notes_to_chef]

  load_and_authorize_resource

def index
  if current_user == nil || current_user.user_type == "Client" 
    if params[:chef][:region].present?
      @chef = Chef.where(region: params[:chef][:region])
      # if @chef.empty?
      #   flash[:notice] = "Sorry no results found."
      # end
    end
  end
  # @chefs = User.where.not(user_type: ['Admin' ,'Client'])
  @all_chefs = Chef.all
end

  def profile
    @galleries = @chef.galleries.where.not(id: nil)
    @gallery = @chef.galleries.build
    @services = @chef.services.where.not(id: nil)
    @service = @chef.services.build
    @appointments = Appointment.where(chef_id: @chef.id)

    @total_rating = 0
    @review_count = 1

    @appointments.each do |a|
      unless a.review.nil?
        @total_rating += a.review.chef_rating
        @review_count += 1
      end
    end

    @total_rating = @total_rating + @chef.rating
    rating = (@total_rating/@review_count).round(0)

    @recipe = Recipe::Client.random
  end
  
  def appointments
  end

  def edit_chef
  end

  def update_chef
    if @chef.update(chef_params)
      redirect_to chef_profile_path(@chef.id), notice: "A user data  was successfully updated"
    else
      flash[:error] = "There are some errors encountered"
      render :edit_chef
    end
  end

  def confirm_appointment
    @appointment = Appointment.find(params[:id])
    @appointment.confirmed_at = Time.now
    @appointment.save
    redirect_to chef_appointments_path, notice: 'Successfully confirmed the appointment'
  end

  def notes_to_chef
    @appointment = Appointment.find(params[:id])
  end

  private

  def set_chef
    @chef = Chef.find(params[:id])
  end

  def set_appointments
    @appointments = Appointment.where(chef_id: current_user.chef.id)
  end

  def chef_params
    params.require(:chef).permit(:contact_number, :bio, :region, :city)
  end
end

app/helpers/chefs_helper.rb
module ChefsHelper

  def charged(balance)
    balance = balance * 0.2
  end

  def payment(balance)
    balance = balance * 0.8
  end
end

app/views/chefs/appointments.html.haml
%link(rel="stylesheet" type="text/css" href="users.scss");

.form.appointments
  %h1 Chef Appointments
  %table
    %thead
      %tr
        %th Chef
        %th Client
        %th Created At
        %th Notes to Chef
        %th Schedule
        %th Total Charge
        %th Confirmed At
        %th Confirm?
        %th Payment Released At
        %th Review
    %tbody
      - @appointments.each do |a|
        %tr
          %td= "#{a.chef.user.first_name} #{a.chef.user.last_name}"
          %td= link_to "#{a.request.client.user.first_name} #{a.request.client.user.last_name}", client_profile_path(a.request.client.id)
          %td= format_date(a.created_at)
          %td
            - if a.request.notes_to_chef.length > 50
              = a.request.notes_to_chef.truncate(50)
              = link_to '...Read more', notes_to_chef_path(@chef.id, a.id), class: ""
            - else
              = a.request.notes_to_chef
          %td
            - if a.schedule 
              = format_schedule(a.schedule)
              = format_schedule_time(a.appointment_time)
            - else
              No schedule yet
          %td= convert_to_money(a.total_charge)
          %td
            - if a.confirmed_at 
              = format_date(a.confirmed_at)
            - else
              Not confirmed
          %td
            - if a.confirmed_at
              confirmed!
            - else
              = link_to 'Confirm?', confirm_appointment_path(current_user.chef.id, a.id), class: "", data: {confirm:"Are you sure?"}
          %td= a.payment_released_at ? format_date(a.payment_released_at) : "No payment yet"
          %td
            - if a.review
              = link_to "Show the review", appointment_review_path(a.id, a.review.id), class: "text-black text-bold" 
            - else
              No Review yet.



app/views/chefs/edit_chef.html.haml
%div{class: "section one"}
  %div{class: "header-left"}
    = link_to :back, class: "waves-effect waves-light btn-small btn-yellow-dark" do
      %i{class: "material-icons left"}arrow_back
      Back
  %div{class: "edit-form z-depth-3"}
    %h3{class: "text-black-dark text-bold"} Update Chef Profile
    = render "devise/shared/error_messages", resource: @chef 
    
    = form_with scope: :chef, url: chef_profile_path, method: :patch do |f|
      %div{class: "field"}
        = f.label :contact_number, class: "label"
        = f.text_field :contact_number, placeholder: "e.g. 09123454432"

      %div{class: "field"}
        = f.label :region, class: "label"
        %select{ name: "chef[region]", required: ""}
          - if @chef.region.nil?
            %option{selected: "selected", value: ""} Select Region
            = CS.states(:ph).each do |key, value|
              %option{id: key, value: value}= value
          - else
            %option{value: ""} Select Region
            = CS.states(:ph).each do |key, value|
              - if @chef.region == value
                %option{id: key, value: value, selected: "selected"}= value
              - else
                %option{id: key, value: value}= value
      
      %div{class: "field"}
        = f.label :city, class: "label"
        = f.text_field :city, placeholder: "City"
      
      %div{class: "field"}
        = f.label :bio, class: "label"
        = f.text_area :bio

      = f.submit("Update Profile", class: "waves-effect waves-light btn-small btn-submit")

app/views/chefs/index.html.haml
%div{class: "section one"}

  - if current_user == nil || current_user.user_type == "Client"
    %div{class: "header-left"}
      = link_to :back, class: "waves-effect waves-light btn-small btn-yellow-dark" do
        %i{class: "material-icons left"}arrow_back
        Back

    %h3{class: "text-black-dark text-bold"} Search Results
    %br
    %br
    %br
    %br
    %br
    %br
    - unless @chef.nil? || @chef.empty?
      - @chef.each do |c|
        %div{class: "review-container"}
          %div{class: "card"}
            %div{class: "card-content"}
              %span{class: "card-name text-black-dark text-bold left"}
                = "Chef " + [c.user.first_name, c.user.last_name].join(' ')
              %span{class: "text-yellow-darker right"}
                - @appointments = Appointment.where(chef_id: c.id)
                - @total_rating = 0
                - @review_count = 0

                - unless @appointments.empty?
                  - @appointments.each do |a|
                    - unless a.review.nil?
                      - @total_rating = @total_rating + a.review.chef_rating
                      - @review_count = @review_count + 1
                
                - if @review_count > 0
                  - @rating = (@total_rating/@review_count).round(0)
                  - case @rating
                  - when 1
                    %i{class: "material-icons left"}star
                    %i{class: "material-icons left"}star_border
                    %i{class: "material-icons left"}star_border
                    %i{class: "material-icons left"}star_border
                    %i{class: "material-icons left"}star_border
                  - when 2
                    %i{class: "material-icons left"}star
                    %i{class: "material-icons left"}star
                    %i{class: "material-icons left"}star_border
                    %i{class: "material-icons left"}star_border
                    %i{class: "material-icons left"}star_border
                  - when 3
                    %i{class: "material-icons left"}star
                    %i{class: "material-icons left"}star
                    %i{class: "material-icons left"}star
                    %i{class: "material-icons left"}star_border
                    %i{class: "material-icons left"}star_border
                  - when 4
                    %i{class: "material-icons left"}star
                    %i{class: "material-icons left"}star
                    %i{class: "material-icons left"}star
                    %i{class: "material-icons left"}star
                    %i{class: "material-icons left"}star_border
                  - when 5
                    %i{class: "material-icons left"}star
                    %i{class: "material-icons left"}star
                    %i{class: "material-icons left"}star
                    %i{class: "material-icons left"}star
                    %i{class: "material-icons left"}star

                - else
                  %i{class: "material-icons left"}star_border
                  %i{class: "material-icons left"}star_border
                  %i{class: "material-icons left"}star_border
                  %i{class: "material-icons left"}star_border
                  %i{class: "material-icons left"}star_border

              %br
              %br

              - unless c.bio.nil? || c.bio == ''
                %p{class: "text-black-dark text-italic"}
                  = '"' + c.bio + '"'
                %br

              %div{class: "card-action"}
                %span{class: "text-black-dark text-italic"}
                  %i{class: "material-icons left"}my_location
                  = [c.city, c.region].join(', ')
                = link_to "Visit Profile", chef_profile_path(c.id), class: "waves-effect waves-light btn-small btn-submit right"
                %br
    - else
      %h5{class: "text-black-light text-italic"} Sorry! No chefs available in the desired region :(
  - else
    %h3{class: "text-black-dark text-bold"} Browse All Chefs
    %br
    %br
    %br
    %br
    %br
    %br
    - unless @all_chefs.nil? || @all_chefs.empty?
      - @all_chefs.each do |c|
        %div{class: "review-container"}
          %div{class: "card"}
            %div{class: "card-content"}
              %span{class: "card-name text-black-dark text-bold left"}
                = "Chef " + [c.user.first_name, c.user.last_name].join(' ')
              %span{class: "text-yellow-darker right"}
                - @appointments = Appointment.where(chef_id: c.id)
                - @total_rating = 0
                - @review_count = 0

                - unless @appointments.empty?
                  - @appointments.each do |a|
                    - unless a.review.nil?
                      - @total_rating = @total_rating + a.review.chef_rating
                      - @review_count = @review_count + 1
                
                - if @review_count > 0
                  - @rating = (@total_rating/@review_count).round(0)
                  - case @rating
                  - when 1
                    %i{class: "material-icons left"}star
                    %i{class: "material-icons left"}star_border
                    %i{class: "material-icons left"}star_border
                    %i{class: "material-icons left"}star_border
                    %i{class: "material-icons left"}star_border
                  - when 2
                    %i{class: "material-icons left"}star
                    %i{class: "material-icons left"}star
                    %i{class: "material-icons left"}star_border
                    %i{class: "material-icons left"}star_border
                    %i{class: "material-icons left"}star_border
                  - when 3
                    %i{class: "material-icons left"}star
                    %i{class: "material-icons left"}star
                    %i{class: "material-icons left"}star
                    %i{class: "material-icons left"}star_border
                    %i{class: "material-icons left"}star_border
                  - when 4
                    %i{class: "material-icons left"}star
                    %i{class: "material-icons left"}star
                    %i{class: "material-icons left"}star
                    %i{class: "material-icons left"}star
                    %i{class: "material-icons left"}star_border
                  - when 5
                    %i{class: "material-icons left"}star
                    %i{class: "material-icons left"}star
                    %i{class: "material-icons left"}star
                    %i{class: "material-icons left"}star
                    %i{class: "material-icons left"}star

                - else
                  %i{class: "material-icons left"}star_border
                  %i{class: "material-icons left"}star_border
                  %i{class: "material-icons left"}star_border
                  %i{class: "material-icons left"}star_border
                  %i{class: "material-icons left"}star_border

              %br
              %br

              - unless c.bio.nil?
                %p{class: "text-black-dark text-italic"}
                  = '"' + c.bio + '"'
                %br

              %div{class: "card-action"}
                %span{class: "text-black-dark text-italic"}
                  %i{class: "material-icons left"}my_location
                  = [c.city, c.region].join(', ')
                = link_to "Visit Profile", chef_profile_path(c.id), class: "waves-effect waves-light btn-small btn-submit right"
                %br

app/views/chefs/notes_to_chef.html.haml
%h1 This Appointment

%span
  = @appointment.request.notes_to_chef

%br
%br

= link_to 'Back', chef_appointments_path(current_user.chef.id)

app/views/chefs/profile.html.erb
<%#= javascript_pack_tag 'toggle', 'data-turbolinks-track': 'reload' %>

<% if current_user.user_type == 'Chef' && current_user.id == @chef.user_id %>
  <%= render '/profiles/profile_own' %>

  <%# add services here (with CREATE, EDIT, DELETE) %>
  <div class="services section two">
    <div class="header-with-btn">
      <h3 class="text-black-dark text-bold">Services<a class="modal-trigger" href="#service-form"><i class="material-icons right">playlist_add</i></a></h3>
    </div>
    
    <div id="service-form" class="modal">
      <div class="modal-content">
        <h4 class="text-italic">Chef Service Form</h4>
        <%= render '/services/form' %>
      </div>
    </div>
    
    <% if @services.empty? %>
      <h5 class="text-black-light text-italic">No available services</h5>
    <% else %>
      <ul class="collection">
        <% @services.each do |service| %>
          <li class="collection-item">
            <div>
              <i class="material-icons left text-yellow-darker" style="font-size: calc(20px + 1 vw) !important;">restaurant</i><span class="text-yellow-dark text-bold" style="font-size: calc(20px + 1 vw) !important; text-transform: uppercase;"><%= service.specialty%></span>
            </div>
            <br>
            <div>
              <i class="material-icons left text-black-light" style="font-size: calc(20px + 1 vw) !important;">person</i><span class="text-black-light text-italic" style="font-size: calc(10px + 1 vw) !important;"><%= convert_to_money(service.service_rate) %> × head</span>

              <%= link_to(chef_service_path(@chef.id, service.id), method: :delete, data: { confirm: 'Are you sure?' }, class: 'text-red') do %>
                <i class="material-icons right">delete</i>
              <% end %>
              
              <%= link_to(edit_chef_service_path(@chef.id, service.id), class: 'text-black-dark') do %>
                <i class="material-icons right">edit</i> 
              <% end %>
            </div>
          </li>
        <% end %>
      </ul>
    <% end %>
  </div>


  <%# add gallery here (with CREATE, EDIT, DELETE)%>
  <div class="gallery section three">
    <div class="header-with-btn">
      <h3 class="text-black-dark text-bold">Gallery<a class="modal-trigger" href="#gallery-form"><i class="material-icons right" style="line-height: 0.25 !important;">add_a_photo</i></a></h3>
    </div>
    
    <div id="gallery-form" class="modal">
      <div class="modal-content">
        <h4 class="text-italic">Upload a Photo</h4>
        <%= render '/galleries/form' %>
      </div>
    </div>
     
      <div class="gallery-container z-depth-4">
        <% if @galleries.empty? %>
          <h5 class="text-black-light text-italic">No available images</h5>
        <% else %>
          <% @galleries.each do |gallery| %>
            <% if gallery.image.attached? %>
              <div class="image-container z-depth-2">
                <div class="delete-container">
                  <%= link_to(chef_gallery_path(@chef.id, gallery.id), method: :delete, data: { confirm: "Are you sure?" }) do %>
                    <i class="material-icons right">clear</i> 
                  <% end %>
                </div>

                <div class="image-frame">
                  <img class="materialboxed" src="<%= (url_for(gallery.image)) %>">
                </div>
              </div>
            <% end %>
          <% end %>
        <% end %>
      </div>
  </div>

<% else %>
  <%# this is profile_own but without the  %>
  <%= render '/profiles/profile_public' %>
  
  <%# add services here %>
  <div class="services section two">
    <h3 class="text-black-dark text-bold">Services</h3>
    
    <% if @services.empty? %>
      <h5 class="text-black-light text-italic">No available services</h5>
    <% else %>
      <ul class="collection">
        <% @services.each do |service| %>
          <li class="collection-item">
            <div>
              <i class="material-icons left text-yellow-darker" style="font-size: calc(20px + 1 vw) !important;">restaurant</i><span class="text-yellow-dark text-bold" style="font-size: calc(20px + 1 vw) !important; text-transform: uppercase;"><%= service.specialty%></span>
            </div>
            <br>
            <div>
              <i class="material-icons left text-black-light" style="font-size: calc(20px + 1 vw) !important;">person</i><span class="text-black-light text-italic" style="font-size: calc(10px + 1 vw) !important;"><%= convert_to_money(service.service_rate) %> × head</span>
            </div>
          </li>
        <% end %>
      </ul>
    <% end %>
  </div>

  <%# add gallery here %>
  <div class="gallery section three">
    <h3 class="text-black-dark text-bold">Gallery</h3>
    
    <% if @galleries.empty? %>
      <h5 class="text-black-light text-italic">No available images</h5>
    <% else %>
      <div class="carousel">
        <% @galleries.each do |gallery| %>
          <% if gallery.image.attached? %>
            <a class="carousel-item"> 
              <div class="image-carousel">
                <img class="materialboxed" src="<%= (url_for(gallery.image)) %>">
              </div>
            </a>
          <% end %>
        <% end %>
      </div>
    <% end %>
  </div>

<% end %>


<div class="reviews section four">
  <h3 class="text-black-dark text-bold">Reviews</h3> 
  <% @review_count = 0 %>
  <% @appointments.each do |a| %>
    <% unless a.review.nil? %>
      <% @review_count = @review_count + 1 %>
    <% end %>
  <% end %>

  <% if @review_count > 0 %>
    <% @appointments.each do |a| %>
      <% unless a.review.nil? %>
        <div class="review-container" style="width: calc(20px + 50vw);">
          <div class="card">
            <div class="card-content">
              <span class="right text-black-dark text-bold">
                <%= format_schedule(a.review.created_at) %>
              </span>

              <br />
              <br />
              
              <p class="text-black-light text-italic">
                "<%= a.review.client_comment %>"
              </p>
              
              <br />

              <span class="text-black-dark text-bold">
                - <%= [a.review.appointment.request.client.user.first_name, a.review.appointment.request.client.user.last_name].join(' ') %>,
                <span class="text-italic">Client</span>
              </span>
            </div>
            <div class="card-action text-yellow-darker">
              <% case a.review.chef_rating  %>
              <% when 1 %>
                <i class="material-icons left">star</i>
                <i class="material-icons left">star_border</i>
                <i class="material-icons left">star_border</i>
                <i class="material-icons left">star_border</i>
                <i class="material-icons left">star_border</i>
              <% when 2 %>
                <i class="material-icons left">star</i>
                <i class="material-icons left">star</i>
                <i class="material-icons left">star_border</i>
                <i class="material-icons left">star_border</i>
                <i class="material-icons left">star_border</i>
              <% when 3 %>
                <i class="material-icons left">star</i>
                <i class="material-icons left">star</i>
                <i class="material-icons left">star</i>
                <i class="material-icons left">star_border</i>
                <i class="material-icons left">star_border</i>
              <% when 4 %>
                <i class="material-icons left">star</i>
                <i class="material-icons left">star</i>
                <i class="material-icons left">star</i>
                <i class="material-icons left">star</i>
                <i class="material-icons left">star_border</i>
              <% when 5 %>
                <i class="material-icons left">star</i>
                <i class="material-icons left">star</i>
                <i class="material-icons left">star</i>
                <i class="material-icons left">star</i>
                <i class="material-icons left">star</i>
              <% end %>
              <span class="text-black-dark"><%= a.review.chef_rating %>/5.0</span>
            </div>
          </div>
        </div>

      <% end %>
    <% end %>
  <% else %>
    <h5 class="text-black-light text-italic">No available reviews</h5>
  <% end %>
</div>

<% if current_user.user_type == 'Chef' && @chef.id == current_user.chef.id %>
  <div class="section one">
    <h3 class="text-black-dark text-bold">Meal Ideas</h3>
    <div class="card">
        <div class="card-image">
          <%= image_tag(@recipe[:data]["meals"][0]["strMealThumb"]) %>
          <span class="card-title"><%= @recipe[:data]["meals"][0]["strMeal"] %></span>
        </div>
        <div class="card-content">
          <p>I am <%= @recipe[:data]["meals"][0]["strMeal"] %>, a simple yet scrumptious meal. I am good for fine-dining experience at home. Want to know more? Click the link below!</p>
        </div>
        <div class="card-action">
          <a href="<%= @recipe[:data]["meals"][0]["strSource"] %>">Click me to know more</a>
        </div>
      </div>
  </div>
<% end %>