config/routes.rb
Rails.application.routes.draw do
  get 'reports/new'
  get 'reviews/new'
  get 'requests/index'
  get 'clients/index'
  get 'chefs/index'
  devise_for :users, :controllers => {:registrations => "my_devise/registrations"}
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'home#index'
  # get 'cities/:state', to: 'application#cities'

  # scope '/admins' do
  #   resources :users
  # end

  # resources :users do
    resources :clients do
      resources :requests
      resources :reports
    end
    resources :chefs do
      resources :galleries
      resources :services
    end
    # end
  resources :appointments do 
    resources :reviews
  end
    
  devise_scope :users do
    get '/client', to: 'clients#index', as: :client_root
    get '/client/:id', to: 'clients#profile', as: :client_profile
    get '/all_chefs', to: 'clients#all_chefs', as: :all_chefs
    put '/client/:id', to: 'clients#update_client'
    patch '/client/:id', to: 'clients#update_client'
    get '/client/:id/edit', to: 'clients#edit_client', as: :edit_client_profile

    get '/chef/:id', to: 'chefs#profile', as: :chef_profile
    get '/chef/:id/appointments', to: 'chefs#appointments', as: :chef_appointments
    get '/chef/:id/appointments/:id', to: 'chefs#notes_to_chef', as: :notes_to_chef
    get '/chef', to: 'chefs#index', as: :chef_root
    put '/chef/:id', to: 'chefs#update_chef'
    patch '/chef/:id', to: 'chefs#update_chef'
    get '/chef/:id/edit', to: 'chefs#edit_chef', as: :edit_chef_profile
    get '/chef/:id/appointments/:id/confirm', to: 'chefs#confirm_appointment', as: :confirm_appointment

    get '/admins', to: 'admins#index', as: :admin_root
    get '/admins/users', to: 'admins#all_users', as: :all_users
    get '/admins/reports', to: 'admins#reports'
    get '/admins/appointments', to: 'admins#appointments'
    get '/admins/transactions', to: 'admins#transactions'
    get '/admins/wallet', to: 'admins#admin_wallet'
    get '/admins/appointments/:id/release', to: 'admins#release_payment', as: :release_payment
    get '/admins/users/:id/suspend_chef', to: 'admins#suspend_chef', as: :suspend_chef
    get '/admins/users/:id/unsuspend_chef', to: 'admins#unsuspend_chef', as: :unsuspend_chef
    get '/admins/users/:id/suspend_client', to: 'admins#suspend_client', as: :suspend_client
    get '/admins/users/:id/unsuspend_client', to: 'admins#unsuspend_client', as: :unsuspend_client
  end

  get '/page-not-found', action: :error_page, controller: 'home'
  # get '*path', to: 'home#error_page'
  

  scope module: 'api', path: 'food', as: 'food' do
    get '/recipe/random', to: 'recipes#random'
  end
end

app/models/client.rb
class Client < ApplicationRecord
  validates :region, :city, :contact_number, presence: true
  
  belongs_to :user
  has_many :requests
  has_many :reports
  has_one :wallet
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController

  before_action :set_client, only: [:profile, :edit_client, :update_client]

  load_and_authorize_resource

  def index
    @name = current_user.first_name + ' ' + current_user.last_name
  end

  def all_chefs
    # @chefs = User.where.not(user_type: ['Admin' ,'Client'])
    @chefs = Chef.all
  end

  def profile
    if current_user.user_type == 'Client'
      @requests = Request.where(client_id: current_user.client.id)
      @requests_array = @requests.map{|req| req.id}
      @appointments = Appointment.where(request_id: @requests_array)
    end
  end

  def edit_client
  end

  def update_client
    if @client.update(client_params)
      redirect_to client_profile_path(@client.id), notice: "A user data  was successfully updated"
    else
      flash[:error] = "There are some errors encountered"
      render :edit_client
    end
  end

  private

  def set_client
    @client = Client.find(params[:id])
  end

  def client_params
    params.require(:client).permit(:contact_number, :region, :city)
  end
  
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/all_chefs.html.haml
%div{class: "section one"}
  %h3{class: "text-black-dark text-bold"} Browse All Chefs
  %br
  %br
  %br
  %br
  %br
  %br
  - unless @chefs.nil? || @chefs.empty?
    - @chefs.each do |c|
      %div{class: "review-container"}
        %div{class: "card"}
          %div{class: "card-content"}
            %span{class: "card-name text-black-dark text-bold left"}
              = "Chef " + [c.user.first_name, c.user.last_name].join(' ')
            %span{class: "text-yellow-darker right"}
              - @appointments = Appointment.where(chef_id: c.id)
              - @total_rating = 0
              - @review_count = 0.99

              - unless @appointments.empty?
                - @appointments.each do |a|
                  - unless a.review.nil?
                    - @total_rating = @total_rating + a.review.chef_rating
                    - @review_count = @review_count + 1

              - @total_rating = @total_rating + c.rating

              - if @review_count > 1
                - @rating = (@total_rating/@review_count).round(0)
                - case @rating
                - when 1
                  %i{class: "material-icons left"}star
                  %i{class: "material-icons left"}star_border
                  %i{class: "material-icons left"}star_border
                  %i{class: "material-icons left"}star_border
                  %i{class: "material-icons left"}star_border
                - when 2
                  %i{class: "material-icons left"}star
                  %i{class: "material-icons left"}star
                  %i{class: "material-icons left"}star_border
                  %i{class: "material-icons left"}star_border
                  %i{class: "material-icons left"}star_border
                - when 3
                  %i{class: "material-icons left"}star
                  %i{class: "material-icons left"}star
                  %i{class: "material-icons left"}star
                  %i{class: "material-icons left"}star_border
                  %i{class: "material-icons left"}star_border
                - when 4
                  %i{class: "material-icons left"}star
                  %i{class: "material-icons left"}star
                  %i{class: "material-icons left"}star
                  %i{class: "material-icons left"}star
                  %i{class: "material-icons left"}star_border
                - when 5
                  %i{class: "material-icons left"}star
                  %i{class: "material-icons left"}star
                  %i{class: "material-icons left"}star
                  %i{class: "material-icons left"}star
                  %i{class: "material-icons left"}star

              - else
                %i{class: "material-icons left"}star_border
                %i{class: "material-icons left"}star_border
                %i{class: "material-icons left"}star_border
                %i{class: "material-icons left"}star_border
                %i{class: "material-icons left"}star_border

            %br
            %br

            - unless c.bio.nil?
              %p{class: "text-black-dark text-italic"}
                = '"' + c.bio + '"'
              %br

            %div{class: "card-action"}
              %span{class: "text-black-dark text-italic"}
                %i{class: "material-icons left"}my_location
                = [c.city, c.region].join(', ')
              = link_to "Visit Profile", chef_profile_path(c.id), class: "waves-effect waves-light btn-small btn-submit right"
              %br
  - else
    %h5{class: "text-black-light text-italic"} Sorry! No chefs available at the moment :(

app/views/clients/edit_client.html.haml
%div{class: "section one"}
  %div{class: "header-left"}
    = link_to :back, class: "waves-effect waves-light btn-small btn-yellow-dark" do
      %i{class: "material-icons left"}arrow_back
      Back
  %div{class: "edit-form z-depth-3"}
    %h3{class: "text-black-dark text-bold"} Update Client Profile
    = render "devise/shared/error_messages", resource: @client

    = form_with scope: :client, url: client_profile_path, method: :patch do |f|
      %div{class: "field"}
        = f.label :contact_number, class: "label"
        = f.text_field :contact_number, placeholder: "e.g. 09123454432"

      %div{class: "field"}
        = f.label :region, class: "label"
        %select{ name: "client[region]", required: ""}
          - if @client.region.nil?
            %option{selected: "selected", value: ""} Select Region
            = CS.states(:ph).each do |key, value|
              %option{id: key, value: value}= value
          - else
            %option{value: ""} Select Region
            = CS.states(:ph).each do |key, value|
              - if @client.region == value
                %option{id: key, value: value, selected: "selected"}= value
              - else
                %option{id: key, value: value}= value

      %div{class: "field"}
        = f.label :city, class: "label"
        = f.text_field :city, placeholder: "City"

      = f.submit("Update Profile", class: "waves-effect waves-light btn-small btn-submit")
  

app/views/clients/index.html.erb
<div class='client-homepage'>
  <div class='banner'>
    <h1 class='banner-header text-yellow-light'>
      Welcome Back, <%=@name%>
    </h1>
    <h4>Ready to experience fine dining at home? Begin by finding the perfect chef for you</h4>
  </div>
</>

app/views/clients/profile.html.erb
<% if current_user.user_type == 'Client' && current_user.id == @client.user_id %>
  <%= render '/profiles/profile_own' %>


  <%# add appointments here%>
  <div class="section two">
    <h3 class="text-black-dark text-bold">Appointments</h3>

    <div class="appointments-container">
      <div class="row">
        <div class="col s12 tabs-container">
          <ul class="tabs">
            <li class="tab col s3"><a href="#confirmed" class="active">Confirmed</a></li>
            <li class="tab col s3"><a href="#pending">Pending</a></li>
            <li class="tab col s3"><a href="#rejected">Rejected</a></li>
            <li class="tab col s3"><a href="#torate">To Rate</a></li>
          </ul>
        </div>
        
        <div id="confirmed" class="tab-content">
          <% @confirmed = 0 %>
          <% @appointments.each do |a| %>
            <% if a.confirmed_at && Date.today < a.schedule %>
              <% @confirmed = @confirmed + 1 %>
              <div class="card appointment">
                <div class="card-content">
                  <div class="avatar-img hide-on-med-and-down">
                    <%= image_tag('chef-2.jpg') %>
                  </div>
                  <div class="text-container"> 
                    <span class="card-title text-black-dark text-bold text-italic">
                      <%= "#{a.chef.user.first_name} #{a.chef.user.last_name}" %>
                    </span>
                    <p class="text-black-light">
                    <span class="text-bold">Schedule: </span>
                      <%= format_schedule(a.schedule) %> 
                      <%= format_schedule_time(a.appointment_time) %> 
                    </p>
                    <br>
                    <p class="text-black-light"><span class="text-bold">Total: </span><%= convert_to_money(a.total_charge) %></p>
                    <p class="text-green text-bold">CONFIRMED</p>

                  </div>
                </div>

                <div class="card-action">
                  <% unless a.review.nil? %>
                    <%= link_to "Show the review", appointment_review_path(a.id, a.review.id), class: "text-bold" %> 
                  <% end %>
                </div>
              </div>
            <% end %>
          <% end %>

          <% if @confirmed == 0 %>
            <h5 class="text-black-light text-italic">Nothing to show here</h5>
          <% end %>
        </div>

        <div id="pending" class="tab-content">
          <% @pending = 0 %>
          <% @appointments.each do |a| %>
            <% unless a.confirmed_at || Date.today >= a.schedule %>
              <% @pending = @pending + 1 %>
              <div class="card appointment">
                <div class="card-content">
                  <div class="avatar-img hide-on-med-and-down">
                    <%= image_tag('chef-2.jpg') %>
                  </div>
                  <div class="text-container"> 
                    <span class="card-title text-black-dark text-bold text-italic">
                      <%= "#{a.chef.user.first_name} #{a.chef.user.last_name}" %>
                    </span>
                    <p class="text-black-light">
                    <span class="text-bold">Schedule: </span>
                    <%= format_schedule(a.schedule) %>
                    <%= format_schedule_time(a.appointment_time) %>
                    </p>
                    <br>
                    <p class="text-black-light"><span class="text-bold">Total: </span><%= convert_to_money(a.total_charge) %></p>
                    <p class="text-yellow-darker text-bold">PENDING</p>
                  </div>
                </div>
              </div>
            <% end %>
          <% end %>
          
          <% if @pending == 0 %>
            <h5 class="text-black-light text-italic">Nothing to show here</h5>
          <% end %>
        </div>

        <div id="rejected" class="tab-content">
          <% @rejected = 0 %>
          <% @appointments.each do |a| %>
            <% unless a.confirmed_at || Date.today < a.schedule %>
              <% @rejected = @rejected + 1 %>
              <div class="card appointment">
                <div class="card-content">
                  <div class="avatar-img hide-on-med-and-down">
                    <%= image_tag('chef-1.jpg') %>
                  </div>
                  <div class="text-container"> 
                    <span class="card-title text-black-dark text-bold text-italic">
                      <%= "#{a.chef.user.first_name} #{a.chef.user.last_name}" %>
                    </span>
                    <p class="text-black-light">
                    <span class="text-bold">Schedule: </span>
                    <%= format_schedule(a.schedule) %>
                    <%= format_schedule_time(a.appointment_time) %>
                    </p>
                    <br>
                    <p class="text-black-light"><span class="text-bold">Total: </span><%= convert_to_money(a.total_charge) %></p>
                    <p class="text-red text-bold">REJECTED</p>
                  </div>
                </div>
              </div>
            <% end %>
          <% end %>
          
          <% if @rejected == 0 %>
            <h5 class="text-black-light text-italic">Nothing to show here</h5>
          <% end %>
          
        </div>
        <div id="torate" class="tab-content">
          <% @to_rate = 0 %>
          <% @appointments.each do |a| %>
            <% if a.review.nil? %>
              <% @to_rate = @to_rate + 1 %>
              <div class="card appointment">
                <div class="card-content">
                  <div class="avatar-img hide-on-med-and-down">
                    <%= image_tag('chef-2.jpg') %>
                  </div>
                  <div class="text-container"> 
                    <span class="card-title text-black-dark text-bold text-italic">
                      <%= "#{a.chef.user.first_name} #{a.chef.user.last_name}" %>
                    </span>
                    <p class="text-black-light">
                    <span class="text-bold">Schedule: </span>
                      <%= format_schedule(a.schedule) %> 
                      <%= format_schedule_time(a.appointment_time) %> 
                    </p>
                    <br>
                    <p class="text-black-light"><span class="text-bold">Total: </span><%= convert_to_money(a.total_charge) %></p>
                    <p class="text-green text-bold">CONFIRMED</p>

                  </div>
                </div>

                <div class="card-action">
                  <% if a.review.nil? %>
                    <%= link_to "Leave a review", new_appointment_review_path(a.id), class: "text-bold" %> 
                  <% else %>
                    <%= link_to "Show the review", appointment_review_path(a.id, a.review.id), class: "text-bold" %> 
                  <% end %>
                </div>
              </div>
            <% end %>
          <% end %>

          <% if @to_rate == 0 %>
            <h5 class="text-black-light text-italic">Nothing to show here</h5>
          <% end %>
        </div>
      </div>
    </div>

  </div>

<% else %>
  <%# this is profile_own but without the wallet and edit profile and shorter section height %>
  <%= render '/profiles/profile_public' %>
<% end %>